package org.alter.plugins.content.economy.audit.report

import org.alter.plugins.content.economy.audit.engine.Finding
import org.alter.plugins.content.economy.audit.engine.LoopClass
import org.alter.plugins.content.economy.audit.engine.Severity
import java.io.File

/** The human report: one section per loop class in the operator's order, then guards, hygiene, coverage. */
object MarkdownWriter {

    fun write(file: File, r: JsonWriter.Report) {
        val sb = StringBuilder()
        val h = r.header
        sb.appendLine("# Economy arbitrage audit (generated)")
        sb.appendLine()
        sb.appendLine("> Generated by `:game-plugins:economyAudit` — do not hand-edit. Re-run: `${h["rerun"]}`")
        sb.appendLine(">")
        sb.appendLine("> git `${h["gitSha"]}` · cache `${h["cachePath"]}` · ${h["generatedAt"]} · plugins constructed ${h["pluginsConstructed"]}, failed ${h["pluginsFailed"]}")
        sb.appendLine()
        sb.appendLine("**Assumptions.** GE commodity backstop treated as enabled (it is switched on by `GrandExchangeEnginePlugin` at world init). " +
            "Hard pegs (NPC sells the currency for gp): ${pegs(r.model.hardPegs, r)}. " +
            "Soft pegs (assumed player-market gp, findings relying on them are marked *soft*): ${pegs(r.model.softPegs, r)}. " +
            "gp/hour uses the crude tick model in the appendix — an order-of-magnitude ranking, not a measurement. " +
            "Numbers are for the **no-fail level** (max level); the *EV@min* columns show the first-usable-level expectation.")
        r.model.notes.forEach { sb.appendLine("> note: $it") }
        sb.appendLine()

        // ---- summary ----
        sb.appendLine("## 1. Summary")
        sb.appendLine()
        val bySev = r.findings.groupBy { it.severity }
        sb.appendLine("| Severity | Count | Meaning |")
        sb.appendLine("|---|---|---|")
        for (s in Severity.values()) {
            val meaning = when (s) {
                Severity.S0 -> "≥ 1,000,000 gp/h sustained, or an unbounded positive cycle"
                Severity.S1 -> "≥ 100,000 gp/h"
                Severity.S2 -> "≥ 10,000 gp/h"
                Severity.S3 -> "≥ 1,000 gp/h"
                Severity.INFO -> "< 1,000 gp/h (hygiene)"
            }
            sb.appendLine("| ${s.name} | ${bySev[s]?.size ?: 0} | $meaning |")
        }
        sb.appendLine()
        sb.appendLine("Loops found: **${r.findings.size}** live · **${r.prevented.size}** prevented by guards · " +
            "**${r.coverage.unexplained.size}** unexplained converter binds · **${r.brokenAdapters.size}** broken recipe adapters.")
        sb.appendLine()
        if (r.findings.isNotEmpty()) {
            sb.appendLine("### Top 25 by sustained gp/hour")
            sb.appendLine()
            findingsTable(sb, r.findings.sortedByDescending { it.gpPerHourSustained }.take(25), showClass = true)
        }

        // ---- per class ----
        sb.appendLine("## 2. Loops by class")
        sb.appendLine()
        var n = 0
        for (cls in LoopClass.values()) {
            val list = r.findings.filter { it.loopClass == cls }
            n++
            sb.appendLine("### 2.$n ${cls.title} (${list.size})")
            sb.appendLine()
            if (list.isEmpty()) { sb.appendLine("_none_"); sb.appendLine(); continue }
            findingsTable(sb, list, showClass = false)
            sb.appendLine("<details><summary>Paths</summary>")
            sb.appendLine()
            for (f in list) paths(sb, f)
            sb.appendLine("</details>")
            sb.appendLine()
        }

        // ---- prevented ----
        sb.appendLine("## 3. Prevented by guards (regression list)")
        sb.appendLine()
        sb.appendLine("Loops that exist in the price data but are blocked by a live guard. If a guard is ever relaxed, these come back.")
        sb.appendLine()
        if (r.prevented.isEmpty()) sb.appendLine("_none_") else {
            sb.appendLine("| Item | Class | Guard(s) | Unguarded profit/unit | Unguarded gp/h | Path |")
            sb.appendLine("|---|---|---|---|---|---|")
            for (f in r.prevented) {
                sb.appendLine("| ${f.itemKey.removePrefix("item.")} | ${f.loopClass.title} | ${f.guardedBy.joinToString(", ")} | ${gp(f.unitProfit)} | ${gp(f.gpPerHourSustained)} | ${shortPath(f)} |")
            }
        }
        sb.appendLine()

        // ---- hygiene ----
        sb.appendLine("## 4. Price hygiene")
        sb.appendLine()
        sb.appendLine("### 4.1 Wares priced below 70% / 60% of cache value (${r.hygiene.belowCost.size})")
        sb.appendLine()
        table(sb, r.hygiene.belowCost, listOf("shop", "item", "currency", "cost", "sell", "buyback70", "alch60"))
        sb.appendLine("### 4.2 Same-shop loops: buyback ≥ shelf price (${r.hygiene.sameShopLoop.size})")
        sb.appendLine()
        table(sb, r.hygiene.sameShopLoop, listOf("shop", "item", "currency", "sell", "buyback"))
        sb.appendLine("### 4.3 One item, several NPC prices (${r.hygiene.inconsistentSell.size})")
        sb.appendLine()
        table(sb, r.hygiene.inconsistentSell, listOf("item", "currency", "prices"))
        sb.appendLine("### 4.4 Cost-0 wares sold at 1 gp (${r.hygiene.zeroCostWares.size})")
        sb.appendLine()
        table(sb, r.hygiene.zeroCostWares, listOf("shop", "item", "currency", "sell"))
        sb.appendLine("### 4.5 Near misses: liquidation is 80–102% of acquisition — do not let repricing flip these (${r.hygiene.nearMiss.size})")
        sb.appendLine()
        table(sb, r.hygiene.nearMiss, listOf("item", "acquire", "liquidate", "ratio", "acquireVia", "liquidateVia"))

        // ---- recipe EV ----
        sb.appendLine("## 5. Recipe expected value (NPC inputs → NPC liquidation)")
        sb.appendLine()
        sb.appendLine("Positive = the recipe mints gp from NPC-bought inputs. `EV@min` = at the first usable level; `no-fail` = at max level.")
        sb.appendLine()
        sb.appendLine("| Recipe | Inputs | Outputs | Input cost | Out (EV@min) | Out (no-fail) | Profit EV@min | Profit no-fail | Note |")
        sb.appendLine("|---|---|---|---|---|---|---|---|---|")
        for (e in r.recipeEv) {
            sb.appendLine("| ${e.edgeId} | ${e.inputs} | ${e.outputs} | ${gp(e.inputCost)} | ${gp(e.outputValueEvMin)} | ${gp(e.outputValueNoFail)} | ${gp(e.profitEvMin)} | ${gp(e.profitNoFail)} | ${e.note}${e.guardedBy?.let { " (guarded: $it)" } ?: ""} |")
        }
        sb.appendLine()

        // ---- coverage ----
        sb.appendLine("## 6. Coverage")
        sb.appendLine()
        sb.appendLine("Bound item-on-item pairs: ${r.coverage.boundItemPairs}; item-on-object pairs: ${r.coverage.boundObjPairs} (from the constructed plugins).")
        sb.appendLine()
        sb.appendLine("### 6.1 Unexplained converter binds — the audit is blind to these (${r.coverage.unexplained.size})")
        sb.appendLine()
        if (r.coverage.unexplained.isEmpty()) sb.appendLine("_none_") else {
            sb.appendLine("| Kind | A | B |"); sb.appendLine("|---|---|---|")
            r.coverage.unexplained.forEach { sb.appendLine("| ${it.kind} | ${it.a} | ${it.b} |") }
        }
        sb.appendLine()
        sb.appendLine("### 6.2 Broken recipe adapters (${r.brokenAdapters.size})")
        sb.appendLine()
        if (r.brokenAdapters.isEmpty()) sb.appendLine("_none_") else r.brokenAdapters.forEach { sb.appendLine("- `${it.first}`: ${it.second}") }
        sb.appendLine()
        sb.appendLine("### 6.3 Allow-listed non-economic binds (${r.coverage.allowlisted.size})")
        sb.appendLine()
        sb.appendLine("<details><summary>show</summary>")
        sb.appendLine()
        r.coverage.allowlisted.forEach { sb.appendLine("- ${it.kind}: ${it.a} × ${it.b}") }
        sb.appendLine()
        sb.appendLine("</details>")
        sb.appendLine()

        // ---- appendix ----
        sb.appendLine("## 7. Appendix")
        sb.appendLine()
        sb.appendLine("### 7.1 Shop snapshot (${r.model.shops.size} shops)")
        sb.appendLine()
        sb.appendLine("| Shop | Currency | Policy | Wares | Explicit prices | Min / max markup vs cost | Buyback allowed |")
        sb.appendLine("|---|---|---|---|---|---|---|")
        for (s in r.model.shops) {
            val markups = s.wares.filter { it.cost > 0 && it.sellPrice != null }.map { it.sellPrice!!.toDouble() / it.cost }
            val mk = if (markups.isEmpty()) "-" else "%.2fx / %.2fx".format(markups.minOrNull(), markups.maxOrNull())
            sb.appendLine("| ${s.name} | ${s.currencyLabel} | ${s.policy}${if (s.sellOnly) " (sell-only)" else ""} | ${s.wares.size} | ${s.wares.count { it.sellPriceSource == "explicit" }} | $mk | ${s.wares.count { it.buybackAllowed }} |")
        }
        sb.appendLine()
        sb.appendLine("### 7.2 Time model")
        sb.appendLine()
        sb.appendLine("| Action | Cost |"); sb.appendLine("|---|---|")
        r.rateTable.forEach { sb.appendLine("| ${it.first} | ${it.second} |") }
        sb.appendLine()
        file.parentFile?.mkdirs()
        file.writeText(sb.toString(), Charsets.UTF_8)
    }

    private fun pegs(m: Map<*, Int>, r: JsonWriter.Report): String =
        if (m.isEmpty()) "none" else m.entries.joinToString(", ") { "${r.model.name(it.key as org.alter.plugins.content.economy.audit.model.NodeId)} = ${it.value} gp" }

    private fun findingsTable(sb: StringBuilder, list: List<Finding>, showClass: Boolean) {
        sb.appendLine("| Sev | Item |${if (showClass) " Class |" else ""} Acquire gp | Liquidate gp | Profit/unit | Margin | gp/h first hour | gp/h sustained | Limit | Flags |")
        sb.appendLine("|---|---|${if (showClass) "---|" else ""}---|---|---|---|---|---|---|---|")
        for (f in list) {
            val flags = buildList {
                if (f.unbounded) add("UNBOUNDED")
                if (f.soft) add("soft")
                if (f.sameShop) add("same-shop")
                if (f.related.isNotEmpty()) add("+${f.related.size} related")
            }.joinToString(" ")
            val margin = if (f.marginPct.isInfinite()) "∞" else "%.0f%%".format(f.marginPct)
            sb.appendLine("| ${f.severity} | ${f.itemKey.removePrefix("item.")} |${if (showClass) " ${f.loopClass.title} |" else ""} ${gp(f.acquireGp)} | ${gp(f.liquidateGp)} | ${gp(f.unitProfit)} | $margin | ${gp(f.gpPerHourFirstHour)} | ${gp(f.gpPerHourSustained)} | ${f.throughput.limitingFactor} | $flags |")
        }
        sb.appendLine()
    }

    private fun paths(sb: StringBuilder, f: Finding) {
        sb.appendLine("**${f.itemKey.removePrefix("item.")}** (${f.severity}) — acquire ${gp(f.acquireGp)} (EV@min ${gp(f.acquireGpEvMin)}), liquidate ${gp(f.liquidateGp)} (EV@min ${gp(f.liquidateGpEvMin)})")
        sb.appendLine()
        f.acquirePath.forEach { sb.appendLine("1. ${it.text}${it.guardedBy?.let { g -> " **[blocked: $g]**" } ?: ""}${if (it.soft) " *(assumed)*" else ""}") }
        f.liquidatePath.forEach { sb.appendLine("1. ${it.text}${it.guardedBy?.let { g -> " **[blocked: $g]**" } ?: ""}${if (it.soft) " *(assumed)*" else ""}") }
        if (f.levelNotes.isNotEmpty()) sb.appendLine("   - levels: ${f.levelNotes.joinToString("; ")}")
        if (f.related.isNotEmpty()) sb.appendLine("   - same loop seen from: ${f.related.joinToString(", ") { it.removePrefix("item.") }}")
        sb.appendLine()
    }

    private fun shortPath(f: Finding): String =
        (f.acquirePath + f.liquidatePath).joinToString(" → ") { it.kind.name.lowercase().replace('_', ' ') }

    private fun table(sb: StringBuilder, rows: List<Map<String, Any?>>, cols: List<String>) {
        if (rows.isEmpty()) { sb.appendLine("_none_"); sb.appendLine(); return }
        sb.appendLine("| " + cols.joinToString(" | ") + " |")
        sb.appendLine("|" + cols.joinToString("") { "---|" })
        for (row in rows) sb.appendLine("| " + cols.joinToString(" | ") { c -> cell(row[c]) } + " |")
        sb.appendLine()
    }

    private fun cell(v: Any?): String = when (v) {
        null -> ""
        is Double -> if (v == Math.floor(v) && Math.abs(v) < 1e12) "%,d".format(v.toLong()) else "%.2f".format(v)
        is Int -> "%,d".format(v)
        is List<*> -> v.joinToString(", ")
        else -> v.toString().replace("|", "\\|")
    }

    private fun gp(d: Double): String = when {
        d.isInfinite() -> "∞"
        d.isNaN() -> "-"
        Math.abs(d) >= 100 -> "%,d".format(Math.round(d))
        else -> "%.1f".format(d)
    }
}
